### ISSUE TITLE
Bash script in Azure Portal Bash shell fails?

### ISSUE THREAD

**Issue by sandervandevelde** [BlueGhostLabs/grafana-container-on-azure#5]
Hello,

I tried to execute the bash shell in the Azure portal.

I got an error on the line 

    client_secret=$(uuidgen)

I got:

    ./bash.sh: line 45: uuidgen: command not found 
    ERROR: argument --password: expected one argument

Is this expected?

(workaround: create a uuid yourself on another linux environment and use that one)

**Comment by phillipsj** [comment]
It looks like the Cloud Shell doesn't have uuidgen installed by default. I don't think they have added those permissions yet, so you may have to pull it down in put it in a code directory and set your path. Nice catch and I should add a note regarding that issue.
