### ISSUE TITLE
No storage - data source and dashboards disappear after restart

### ISSUE THREAD

**Issue by sandervandevelde** [BlueGhostLabs/grafana-container-on-azure#6]
After restarting, any create data sources and dashboards disappear. The settings are not persisted anymore :-(

Is there another solution as a fix for the deprecated storage account support?

Any suggestion is welcome...

**Comment by phillipsj** [comment]
@sandervandevelde yet, I removed that functionality as it was no longer supported on the Azure side. It seems that there maybe some changes regarding it. Here is the post I did about it. https://www.phillipsj.net/posts/update-easy-grafana-on-azure/
